import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import * as nodemailer from 'nodemailer';
import { addMonths, differenceInDays } from 'date-fns';

export async function GET(request: NextRequest) {
  try {
    const authHeader = request.headers.get('authorization');
    if (!process.env.CRON_SECRET || authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const allSettings = await prisma.expiryAlertSettings.findMany({
      where: {
        OR: [
          { enableWhatsApp: true },
          { enableEmail: true }
        ]
      },
      include: {
        shop: {
          select: { name: true }
        }
      }
    });

    if (allSettings.length === 0) {
      return NextResponse.json({ success: true, shopsProcessed: 0, message: 'No shops with alerts enabled' });
    }

    let shopsProcessed = 0;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const sixMonthsFromNow = addMonths(today, 6);

    for (const settings of allSettings) {
      const batches = await prisma.inventoryBatch.findMany({
        where: {
          shopId: settings.shopId,
          stockQty: { gt: 0 },
          expiryDate: { lte: sixMonthsFromNow },
        },
        include: {
          medicine: {
            select: { name: true, company: true, mrp: true },
          },
        },
        orderBy: { expiryDate: 'asc' },
      });

      if (batches.length === 0) continue;

      const buckets = {
        expired: [] as string[],
        month1: [] as string[],
        month2: [] as string[],
        month3: [] as string[],
        month4: [] as string[],
        month5: [] as string[],
        month6: [] as string[],
      };

      for (const batch of batches) {
        const daysDiff = differenceInDays(new Date(batch.expiryDate), today);
        const itemText = `- ${batch.medicine.name} | ${batch.medicine.company} | ₹${Number(batch.medicine.mrp || 0).toFixed(2)}`;
        
        if (daysDiff < 0) buckets.expired.push(itemText);
        else if (daysDiff <= 30) buckets.month1.push(itemText);
        else if (daysDiff <= 60) buckets.month2.push(itemText);
        else if (daysDiff <= 90) buckets.month3.push(itemText);
        else if (daysDiff <= 120) buckets.month4.push(itemText);
        else if (daysDiff <= 150) buckets.month5.push(itemText);
        else if (daysDiff <= 180) buckets.month6.push(itemText);
      }

      const dateStr = today.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
      let messageText = `📋 MONTHLY EXPIRY REPORT\n🏪 ${settings.shop.name}\n📅 ${dateStr}\n━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

      if (buckets.expired.length > 0) messageText += `🔴 EXPIRED\n${buckets.expired.join('\n')}\n\n`;
      if (buckets.month1.length > 0) messageText += `🚨 EXPIRING IN 1 MONTH\n${buckets.month1.join('\n')}\n\n`;
      if (buckets.month2.length > 0) messageText += `⚠️ EXPIRING IN 2 MONTHS\n${buckets.month2.join('\n')}\n\n`;
      if (buckets.month3.length > 0) messageText += `📌 EXPIRING IN 3 MONTHS\n${buckets.month3.join('\n')}\n\n`;
      if (buckets.month4.length > 0) messageText += `📌 EXPIRING IN 4 MONTHS\n${buckets.month4.join('\n')}\n\n`;
      if (buckets.month5.length > 0) messageText += `📌 EXPIRING IN 5 MONTHS\n${buckets.month5.join('\n')}\n\n`;
      if (buckets.month6.length > 0) messageText += `📌 EXPIRING IN 6 MONTHS\n${buckets.month6.join('\n')}\n\n`;

      messageText += `━━━━━━━━━━━━━━━━━━━━━━━━━━\n✅ Report generated by Ayur-stock Pro`;

      if (settings.enableEmail && settings.emailAddress) {
        try {
          const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST || 'smtp.gmail.com',
            port: parseInt(process.env.SMTP_PORT || '587'),
            secure: process.env.SMTP_PORT === '465',
            auth: {
              user: process.env.SMTP_USER,
              pass: process.env.SMTP_PASS,
            },
          });

          const monthName = today.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });
          await transporter.sendMail({
            from: process.env.SMTP_FROM || `"Ayur-stock Pro" <${process.env.SMTP_USER}>`,
            to: settings.emailAddress,
            subject: `Monthly Expiry Report — ${settings.shop.name} — ${monthName}`,
            text: messageText,
          });
        } catch (e) {
          console.error(`Cron Email Error for Shop ${settings.shopId}:`, e);
        }
      }

      // Note: WhatsApp messages cannot be sent directly via code unless using Twilio API/WhatsApp Cloud API.
      // Since this is a CRON job, we can't 'open a window'. We will just send Emails in this loop unless they have an API integration.
      // The user specifically stated "WhatsApp sending opens in browser via wa.me link — this is intentional, same as rest of the app". 
      // This implies WhatsApp is manually triggered inside `<ExpiryAlertSettings />` when the user clicks 'Send Expiry Report'.
      
      shopsProcessed++;
    }

    return NextResponse.json({ success: true, shopsProcessed });
  } catch (error) {
    console.error('Cron Expiry Alerts Error:', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}
