import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { authenticateRequest, createApiResponse, createErrorResponse } from '@/middleware/auth';
import * as nodemailer from 'nodemailer';
import { addMonths, differenceInDays } from 'date-fns';

export async function POST(request: NextRequest) {
  try {
    const auth = await authenticateRequest(request);
    if (!auth) {
      return createErrorResponse('Unauthorized', 401);
    }

    const shopId = auth.user.shopId;

    const shop = await prisma.shop.findUnique({
      where: { id: shopId },
      select: { name: true }
    });

    if (!shop) {
      return createErrorResponse('Shop not found', 404);
    }

    const settings = await prisma.expiryAlertSettings.findUnique({
      where: { shopId },
    });

    if (!settings || (!settings.enableWhatsApp && !settings.enableEmail)) {
      return createApiResponse(true, { message: 'Alerts are disabled', buckets: {} });
    }

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const sixMonthsFromNow = addMonths(today, 6);

    const batches = await prisma.inventoryBatch.findMany({
      where: {
        shopId,
        stockQty: { gt: 0 },
        expiryDate: { lte: sixMonthsFromNow },
      },
      include: {
        medicine: {
          select: { name: true, company: true, mrp: true },
        },
      },
      orderBy: { expiryDate: 'asc' },
    });

    const buckets = {
      expired: [] as any[],
      month1: [] as any[],
      month2: [] as any[],
      month3: [] as any[],
      month4: [] as any[],
      month5: [] as any[],
      month6: [] as any[],
    };

    const bucketCounts = {
      expired: 0,
      month1: 0,
      month2: 0,
      month3: 0,
      month4: 0,
      month5: 0,
      month6: 0,
    };

    for (const batch of batches) {
      const daysDiff = differenceInDays(new Date(batch.expiryDate), today);
      const itemText = `- ${batch.medicine.name} | ${batch.medicine.company} | ₹${Number(batch.medicine.mrp || 0).toFixed(2)}`;
      
      if (daysDiff < 0) {
        buckets.expired.push(itemText);
        bucketCounts.expired++;
      } else if (daysDiff <= 30) {
        buckets.month1.push(itemText);
        bucketCounts.month1++;
      } else if (daysDiff <= 60) {
        buckets.month2.push(itemText);
        bucketCounts.month2++;
      } else if (daysDiff <= 90) {
        buckets.month3.push(itemText);
        bucketCounts.month3++;
      } else if (daysDiff <= 120) {
        buckets.month4.push(itemText);
        bucketCounts.month4++;
      } else if (daysDiff <= 150) {
        buckets.month5.push(itemText);
        bucketCounts.month5++;
      } else if (daysDiff <= 180) {
        buckets.month6.push(itemText);
        bucketCounts.month6++;
      }
    }

    const dateStr = today.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
    let messageText = `📋 MONTHLY EXPIRY REPORT\n🏪 ${shop.name}\n📅 ${dateStr}\n━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    if (buckets.expired.length > 0) {
      messageText += `🔴 EXPIRED\n${buckets.expired.join('\n')}\n\n`;
    }
    if (buckets.month1.length > 0) {
      messageText += `🚨 EXPIRING IN 1 MONTH\n${buckets.month1.join('\n')}\n\n`;
    }
    if (buckets.month2.length > 0) {
      messageText += `⚠️ EXPIRING IN 2 MONTHS\n${buckets.month2.join('\n')}\n\n`;
    }
    if (buckets.month3.length > 0) {
      messageText += `📌 EXPIRING IN 3 MONTHS\n${buckets.month3.join('\n')}\n\n`;
    }
    if (buckets.month4.length > 0) {
      messageText += `📌 EXPIRING IN 4 MONTHS\n${buckets.month4.join('\n')}\n\n`;
    }
    if (buckets.month5.length > 0) {
      messageText += `📌 EXPIRING IN 5 MONTHS\n${buckets.month5.join('\n')}\n\n`;
    }
    if (buckets.month6.length > 0) {
      messageText += `📌 EXPIRING IN 6 MONTHS\n${buckets.month6.join('\n')}\n\n`;
    }

    messageText += `━━━━━━━━━━━━━━━━━━━━━━━━━━\n✅ Report generated by Ayur-stock Pro`;

    let emailSent = false;
    let emailError = null;

    if (settings.enableEmail && settings.emailAddress) {
      try {
        const transporter = nodemailer.createTransport({
          host: process.env.SMTP_HOST || 'smtp.gmail.com',
          port: parseInt(process.env.SMTP_PORT || '587'),
          secure: process.env.SMTP_PORT === '465',
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
          },
        });

        const monthName = today.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });
        await transporter.sendMail({
          from: process.env.SMTP_FROM || `"Ayur-stock Pro" <${process.env.SMTP_USER}>`,
          to: settings.emailAddress,
          subject: `Monthly Expiry Report — ${shop.name} — ${monthName}`,
          text: messageText,
        });
        emailSent = true;
      } catch (e: any) {
        console.error('Failed to send email:', e);
        emailError = e.message;
      }
    }

    let whatsappUrl = null;
    if (settings.enableWhatsApp && settings.whatsappNumber) {
      whatsappUrl = `https://wa.me/${settings.whatsappNumber.replace(/\D/g, '')}?text=${encodeURIComponent(messageText)}`;
    }

    return createApiResponse(true, {
      message: 'Report processed',
      buckets: bucketCounts,
      whatsappUrl,
      emailSent,
      emailError
    });
  } catch (error) {
    console.error('Send expiry report error:', error);
    return createErrorResponse('Internal server error', 500);
  }
}
